#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/edgeidx
#
# IDENTIFICATION
#    src/backend/access/edgeidx/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/edgeidx
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = edgeidx.o eiinsert.o eisearch.o eipage.o

include $(top_srcdir)/src/backend/common.mk
