#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ein
#
# IDENTIFICATION
#    src/backend/access/ein/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ein
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = ein.o eininsert.o einpage.o einsearch.o einsort.o

include $(top_srcdir)/src/backend/common.mk
