#-------------------------------------------------------------------------
#
# Makefile for src/submodules (AgensGraph Submodules)
#
# Copyright (c) 2022 by Bitnine Global, Inc.
#
# src/submodules/Makefile
#
#-------------------------------------------------------------------------

subdir = src/submodules
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = orioledb

$(recurse)
$(recurse_always)
